# Generated by Django 4.2.1 on 2023-06-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('Children', 'Children'), ('Women', 'Women')], max_length=255, verbose_name='Категория'),
        ),
    ]
