# Generated by Django 4.2.1 on 2023-06-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_categories_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='Message',
        ),
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(choices=[('Children', 'Children'), ('Women', 'Women'), ('Men', 'Men')], max_length=255, verbose_name='Категория'),
        ),
    ]
